spring:
  application:
    name: EMPLOYEE-SERVICE
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  config:
    import: optional:configserver:http://localhost:8888

#application:
#  title: Employee Service
#  version: v1.0
#  project-dir: /employee
#
#logging:
#  level:
#    ROOT: INFO
#
## Server Configuration
#server:
#  port: 8085
#  servlet:
#    context-path: /employee
##  ssl:
##    key-store: /etc/letsencrypt/live/employee.xxx.xxx.azure.com/keystore.p12
##    key-store-type: PKCS12
##    key-store-password: test
##    key-alias: test
#
## Spring Configurations
#spring:
#  application:
#    name: EMPLOYEE-SERVICE
#
## OpenAPI Configurations
#openapi:
#  title: Employee Service
#  version: v1.0
#  description: Employee REST API Service
#  termsOfService:
#  contact:
#    email:
#    name:
#    url:
#  license:
#    name:
#    url:
#
## Default Open API endpoint Specifications
## api docs endpoint path
#springdoc:
#  api-docs.path: /v3/api-docs
#  # customise endpoint for Swagger UI
#  swagger-ui:
#    path: /swagger-ui
#    # disable default Swagger
#    disable-swagger-default-url: true
#    # disable schemas/models in swagger ui
#    defaultModelsExpandDepth=-1:
#
##web-config-origin-url
#web:
#  config:
#    allowed-origin-urls: http://localhost:3000,
#      http://localhost:3001,
#      http://localhost:3002,
#    max-age: 3600
#
#eureka:
#  instance:
#    client:
#      server:
#        url:
#          default-zone: http://localhost:8761/eureka/