spring:
  application:
    name: ORGANIZATION-SERVICE

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  config:
    import: optional:configserver:http://localhost:8888

  zipkin:
    base-url: http://127.0.0.1:9411/

management: # number of requests zipkin or micrometer can send to sleuth to visualize the trace
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  retry: # Retry configuration
    instances:
      ORGANIZATION-SERVICE:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 2s
  circuitbreaker:  # circuitbreaker configuration
    instance:
      ORGANIZATION-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

#application:
#  title: ORGANIZATION Service
#  version: v1.0
#  project-dir: /organization
#
#logging:
#  level:
#    ROOT: INFO
#
## Server Configuration
#server:
#  port: 8083
#  servlet:
#    context-path: /organization
##  ssl:
##    key-store: /etc/letsencrypt/live/employee.xxx.xxx.azure.com/keystore.p12
##    key-store-type: PKCS12
##    key-store-password: test
##    key-alias: test
#
## Spring Configurations
#spring:
#  application:
#    name: ORGANIZATION-SERVICE
#
## OpenAPI Configurations
#openapi:
#  title: Organization Service
#  version: v1.0
#  description: Organization REST API Service
#  termsOfService:
#  contact:
#    email:
#    name:
#    url:
#  license:
#    name:
#    url:
#
## Default Open API endpoint Specifications
## api docs endpoint path
#springdoc:
#  api-docs.path: /v3/api-docs
#  # customise endpoint for Swagger UI
#  swagger-ui:
#    path: /swagger-ui
#    # disable default Swagger
#    disable-swagger-default-url: true
#    # disable schemas/models in swagger ui
#    defaultModelsExpandDepth=-1:
#
##web-config-origin-url
#web:
#  config:
#    allowed-origin-urls: http://localhost:3000,
#      http://localhost:3001,
#      http://localhost:3002,
#    max-age: 3600
#
#eureka:
#  instance:
#    client:
#      server:
#        url:
#          default-zone: http://localhost:8761/eureka/